### ISSUE TITLE
support latest NodeJS versions

### ISSUE THREAD

**Issue by sebbsan** [commercetools/commercetools-sunrise-data#132]
This repository should not have the restriction to support NodeJS versions smaller than 10

**Comment by stuartcrump** [comment]
Is there going to be support for a later version of Node?  I'm using ^12 and there are install issues.

**Comment by harm-meijer** [comment]
> Is there going to be support for a later version of Node? I'm using ^12 and there are install issues.

Yes, we [are working on improvements](https://github.com/commercetools/commercetools-sunrise-data/blob/env-refactoring/package.json#L90) and plan to release it this Thursday 16th Jan 2020.

I would not advice using that branch now as there are some fixes that are yet to be merged but that branch will be released this week.

**Comment by stuartcrump** [comment]
> > Is there going to be support for a later version of Node? I'm using ^12 and there are install issues.
> 
> Yes, we [are working on improvements](https://github.com/commercetools/commercetools-sunrise-data/blob/env-refactoring/package.json#L90) and plan to release it this Thursday 16th Jan 2020.
> 
> I would not advice using that branch now as there are some fixes that are yet to be merged but that branch will be released this week.

Thanks - I'm keen to install the product catalogue as I'm using the 60day Trial, so keen to have this fixed so I can run the install without errors.  At the moment I've several npm High and Moderate errors.

**Comment by harm-meijer** [comment]
@stuartcrump On Thursday we will merge [this branch](https://github.com/amsterdamharu/commercetools-sunrise-data/tree/env-refactoring) from my repo into `env-refactoring` of commercetools, [here](https://github.com/commercetools/commercetools-sunrise-data/pull/150) is the pull request.

You could clone [my repo](https://github.com/amsterdamharu/commercetools-sunrise-data/tree/env-refactoring#3-set-your-commercetools-project-credentials), checkout  the `env-refactoring` branch with the following command `git checkout env-refactoring` and run the import, please check the readme because you need to set the [credentials in a different way](https://github.com/amsterdamharu/commercetools-sunrise-data/tree/env-refactoring#3-set-your-commercetools-project-credentials).

If you plan to work with the [sunrise-spa](https://github.com/commercetools/sunrise-spa) then make sure you follow the [alternative instructions](https://github.com/commercetools/sunrise-spa/issues/168#issuecomment-567044472).

If you have any problems please let me know.

**Comment by stuartcrump** [comment]
@harm-meijer thanks for the update.  I'll wait for the merge so I can just pull the update down, I'm not in a rush to do this now - just had some free time.  Plan is to look at integration with Acoustic Content (acoustic.co) CMS.  Unsure of the use cases at the moment.

**Comment by harm-meijer** [comment]
The new release can be used with latest node.
